---
title: "Spotify Music Project"
author: "RiSK: Rhea Tejwani, Sue Zhang, Keena Gao"
date: "10/25/20"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE, 
                      message = FALSE)
```

Your written report goes here! Before you submit, make sure your code chunks are turned off with `echo = FALSE` and there are no warnings or messages with `warning = FALSE` and `message = FALSE` 

#Introduction
  The dataset contains statistics of the most popular music in the world over the years on the streaming service
Spotify. Music is constantly changing, and as students who frequently listen to music, we want to analyze the
trends of popular music in our generation and the generations before us. Our research question is “how have
characteristics of the most listened to music changed over time?” Our hypotheses are that popular music has
shifted to be more diverse in these categories like acoustics, BPM, valence, etc.
  This data set has 15 columns and 1994 rows. The observations in the data set describe the characteristics
of the top 2000 most popular songs from 1956 to 2019 from Spotify. Title: title of the song Artist: the
musician/group who performed the song Top genre: genre of the track year: year it was released Beats per
minute(bpm): tempo of the song Energy: how energetic the song is Danceability: how easy the song is
to dance to Loudness(dB): how loud the song is Liveness: the likeliness of the song being a live recording
Valence: how positive a song is Length(duration): the length of a track Acousticness: how acoustic a song is
Speechiness: how much spoken word is in the song Popularity: how popular a song is
The original data set was taken from the playlist on spotify Top 2000s on PlaylistMachinery(@plamere) using
Selenium with Python. It was scraped from http://sortyourmusic.playlistmachinery.com/.

# Methodology

  We will look at the correlation, variance and IQR of the variables for beats per minute, energy, valence, acousticness and speechiness. We will visualize our data using ggplot with scatterplots, boxplots and histograms. We will try to use linear models and the tools from library(broom). We can use summary statistics to find the mean, median and range of our data. We will also use the library(tidyverse) functions to explore our data set. We will find the p-value and use hypothesis tests to analyze the statistical significance of our tests.
  



